### PR TITLE
add stream support

### PR DESCRIPTION
**Pull request by xiao333ma**
Add stream support according to [event_stream_format](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#event_stream_format)

### CODE REVIEW

**Comment by otiai10** [comment]
Thank you for your suggestion. Using callback function is a great idea to deal with async response in for example JavaScript, however, I'd like to take different approach like `chan` in this Go code.

**Comment by otiai10** [comment]
relate #9

**Comment by Naist4869** [comment]
resp, err := client.HTTPClient.Do(req)
check err and close body

**Comment by Naist4869** [comment]
maybe try generic function

**Comment by Naist4869** [comment]
Maybe set header X-Accel-Buffering: no for nginx

**Comment by otiai10** [comment]
Guys, thank you for your comments. I created a pull-request regarding `stream` option. https://github.com/otiai10/openaigo/pull/11
Please take a look and leave comments when you have a time.

**Comment by Naist4869** [comment]
> 伙计们，谢谢你的评论。我创建了一个关于选项的拉取请求`stream`。#11 有时间请看一看并发表评论。

Current version non-streaming requests do not go swich default

Maybe try
```go
type Streamble[T any] interface {
	Stream() <-chan T
}
	v, ok := (response).(Streamble[any])
	if ok {
		if v.Stream() != nil {
			go handle(v.Stream(), httpres.Body)
			return nil
		}
	}
	return decode(response, httpres.Body)
```

**Comment by otiai10** [comment]
Thank you @xiao333ma and @Naist4869.
After taking some time to write a bunch of code based on my idea with `chan`, for more safety and usability, I came to the conclusion that using callback is better.
Let me respect your commit and I'll merge it into develop branch later. Please stay tuned and thank you for your initiative.

**Pull request closed without merging**
